<?php

declare(strict_types=1);

namespace Tests\Integration;

final class GeneratedPostmanStatusTest extends IntegrationTestCase
{
    /**
     * @dataProvider postmanStatusCases
     */
    public function test_postman_status_case(string $name, string $method, string $path, int $expectedStatus): void
    {
        if (getenv('RUN_GENERATED_POSTMAN') !== '1') {
            self::markTestSkipped('Generated Postman matrix is opt-in. Set RUN_GENERATED_POSTMAN=1 to execute.');
        }

        if (!str_starts_with($path, '/auth') && !str_starts_with($path, '/webhook')) {
            $this->loginAdmin();
        }

        $response = $this->client->request($method, $path);
        self::assertSame($expectedStatus, $response['status'], $name . " failed for " . $path);
    }

    public static function postmanStatusCases(): array
    {
        return [
            'Auth/Auth - Invalid password' => ['Auth/Auth - Invalid password', 'POST', '/auth', 401],
            'Auth/Auth - Invalid password2' => ['Auth/Auth - Invalid password2', 'POST', '/auth', 401],
            'Auth/Auth - Invalid password3' => ['Auth/Auth - Invalid password3', 'POST', '/auth', 401],
            'Auth/Auth - Invalid password4' => ['Auth/Auth - Invalid password4', 'POST', '/auth', 401],
            'Auth/Auth - Invalid password5' => ['Auth/Auth - Invalid password5', 'POST', '/auth', 401],
            'Auth/Auth - Invalid password6' => ['Auth/Auth - Invalid password6', 'POST', '/auth', 401],
            'Auth/Auth - Prerequest Test Status' => ['Auth/Auth - Prerequest Test Status', 'GET', '/status', 200],
            'Auth/Auth - Refresh Tokens' => ['Auth/Auth - Refresh Tokens', 'GET', '/auth/refresh', 200],
            'Auth/Auth - Test Expired Access Token' => ['Auth/Auth - Test Expired Access Token', 'GET', '/status', 401],
            'Auth/Auth - User ID not in db' => ['Auth/Auth - User ID not in db', 'GET', '/bank_account', 401],
            'Auth/Auth - logout' => ['Auth/Auth - logout', 'DELETE', '/auth/revoke', 200],
            'BankAccount/Bank Account - Read All' => ['BankAccount/Bank Account - Read All', 'GET', '/bank_account', 200],
            'BankAccount/Bank Account - Read One ID' => ['BankAccount/Bank Account - Read One ID', 'GET', '/bank_account/2', 200],
            'BankAccount/Bank Account- Read One Name' => ['BankAccount/Bank Account- Read One Name', 'GET', '/bank_account/paypal', 200],
            'CleanUp - Revoke Tokens' => ['CleanUp - Revoke Tokens', 'DELETE', '/auth/revoke', 200],
            'Country/Country - Read' => ['Country/Country - Read', 'GET', '/country', 200],
            'Country/Country - Read One ID' => ['Country/Country - Read One ID', 'GET', '/country/2', 200],
            'Country/Country - Read One Name' => ['Country/Country - Read One Name', 'GET', '/country/Zimb', 200],
            'Email/Email: Prepare Reminder' => ['Email/Email: Prepare Reminder', 'POST', '/email/prepare_reminder', 200],
            'Email/Email: Prepare Switch Request' => ['Email/Email: Prepare Switch Request', 'POST', '/email/prepare_switchrequest', 200],
            'Email/Email: Send Reminder' => ['Email/Email: Send Reminder', 'POST', '/email/send_reminder', 200],
            'Filter/Filter - Address' => ['Filter/Filter - Address', 'GET', '/members/filter?address=september&removed=y', 200],
            'Filter/Filter - Any' => ['Filter/Filter - Any', 'GET', '/members/filter?removed=any', 200],
            'Filter/Filter - Any & empty Biz or Surname' => ['Filter/Filter - Any & empty Biz or Surname', 'GET', '/members/filter?removed=any&businessorsurname=', 200],
            'Filter/Filter - Bank Account' => ['Filter/Filter - Bank Account', 'GET', '/members/filter?bankaccountid=1', 200],
            'Filter/Filter - Biz Name' => ['Filter/Filter - Biz Name', 'GET', '/members/filter?businessname=bonha', 200],
            'Filter/Filter - Blank Body' => ['Filter/Filter - Blank Body', 'GET', '/members/filter', 200],
            'Filter/Filter - Cox' => ['Filter/Filter - Cox', 'GET', '/members/filter?surname=cox', 200],
            'Filter/Filter - DeleteDate' => ['Filter/Filter - DeleteDate', 'GET', '/members/filter?deletedatestart=2020-06-01&deletedateend=2020-08-31', 200],
            'Filter/Filter - Deleted' => ['Filter/Filter - Deleted', 'GET', '/members/filter?removed=y', 200],
            'Filter/Filter - Email' => ['Filter/Filter - Email', 'GET', '/members/filter?email=jeffest', 200],
            'Filter/Filter - ExpiryDate (endonly)' => ['Filter/Filter - ExpiryDate (endonly)', 'GET', '/members/filter?expirydateend=2020-12-31', 200],
            'Filter/Filter - ExpiryDate (start only)' => ['Filter/Filter - ExpiryDate (start only)', 'GET', '/members/filter?expirydatestart=2020-12-31', 200],
            'Filter/Filter - Has Email (any)' => ['Filter/Filter - Has Email (any)', 'GET', '/members/filter?hasemail=any', 200],
            'Filter/Filter - Has Email (n)' => ['Filter/Filter - Has Email (n)', 'GET', '/members/filter?hasemail=n', 200],
            'Filter/Filter - Has Email (y)' => ['Filter/Filter - Has Email (y)', 'GET', '/members/filter?hasemail=y', 200],
            'Filter/Filter - Invalid Date' => ['Filter/Filter - Invalid Date', 'GET', '/members/filter?expirydateend=2020-12-310', 422],
            'Filter/Filter - Invalid Surname' => ['Filter/Filter - Invalid Surname', 'GET', '/members/filter?surname=asfdkjhsakf', 200],
            'Filter/Filter - LastTransaction Date' => ['Filter/Filter - LastTransaction Date', 'GET', '/members/filter?lasttransactiondatestart=2020-12-01&lasttransactiondateend=2020-12-31', 200],
            'Filter/Filter - LastTransaction Type Cash' => ['Filter/Filter - LastTransaction Type Cash', 'GET', '/members/filter?paymentmethod=cash', 200],
            'Filter/Filter - LastTransaction Type Cheque' => ['Filter/Filter - LastTransaction Type Cheque', 'GET', '/members/filter?paymentmethod=cheq&lasttransactiondateend=2021-02-08', 200],
            'Filter/Filter - Membership Type' => ['Filter/Filter - Membership Type', 'GET', '/members/filter?membertypeid=5', 200],
            'Filter/Filter - Membership Type Range' => ['Filter/Filter - Membership Type Range', 'GET', '/members/filter?membertyperange=5,6', 200],
            'Filter/Filter - Not Deleted' => ['Filter/Filter - Not Deleted', 'GET', '/members/filter?removed=n', 200],
            'Filter/Filter - PaymentType' => ['Filter/Filter - PaymentType', 'GET', '/members/filter?paymenttypeid=5', 200],
            'Filter/Filter - ReminderDate' => ['Filter/Filter - ReminderDate', 'GET', '/members/filter?reminderdatestart=2020-06-01&reminderdateend=2020-06-30', 200],
            'Filter/Filter - Surname' => ['Filter/Filter - Surname', 'GET', '/members/filter?surname=bha&removed=any', 200],
            'Filter/Filter - Surname or Biz Name' => ['Filter/Filter - Surname or Biz Name', 'GET', '/members/filter?businessorsurname=car&removed=any', 200],
            'Filter/Filter - UpdateDate' => ['Filter/Filter - UpdateDate', 'GET', '/members/filter?updatedatestart=2021-01-01&updatedateend=2021-01-31&removed=any', 200],
            'Member/Member - Check Update Worked 2' => ['Member/Member - Check Update Worked 2', 'GET', '/member/278', 200],
            'Member/Member - Create New' => ['Member/Member - Create New', 'POST', '/member', 200],
            'Member/Member - Get ID of New Member' => ['Member/Member - Get ID of New Member', 'GET', '/member', 200],
            'Member/Member - Read All' => ['Member/Member - Read All', 'GET', '/member', 200],
            'Member/Member - Read One ID' => ['Member/Member - Read One ID', 'GET', '/member/469', 200],
            'Member/Member - Read One ID Copy' => ['Member/Member - Read One ID Copy', 'GET', '/member/418', 200],
            'Member/Member - Update 2' => ['Member/Member - Update 2', 'PUT', '/member/278', 200],
            'Member/Member- Set Geometry Copy' => ['Member/Member- Set Geometry Copy', 'PATCH', '/member/1', 200],
            'Members/Members - Anonymize Old Former Members' => ['Members/Members - Anonymize Old Former Members', 'PATCH', '/members/oldformermember/60', 200],
            'Members/Members - CEM' => ['Members/Members - CEM', 'GET', '/members/cem', 200],
            'Members/Members - CSV Mailing List' => ['Members/Members - CSV Mailing List', 'GET', '/members/mailinglist', 200],
            'Members/Members - Count' => ['Members/Members - Count', 'GET', '/members/summary', 200],
            'Members/Members - Discount' => ['Members/Members - Discount', 'GET', '/members/discount', 200],
            'Members/Members - Duplicate payers' => ['Members/Members - Duplicate payers', 'GET', '/members/duplicatepayers', 200],
            'Members/Members - Email List' => ['Members/Members - Email List', 'GET', '/members/emaillist', 200],
            'Members/Members - Former Member 12m' => ['Members/Members - Former Member 12m', 'GET', '/members/formermember/18', 200],
            'Members/Members - Invalid Emails' => ['Members/Members - Invalid Emails', 'GET', '/members/invalidemails', 200],
            'Members/Members - Invalid Postcodes' => ['Members/Members - Invalid Postcodes', 'GET', '/members/invalidpostcodes', 200],
            'Members/Members - Invalid Report Name' => ['Members/Members - Invalid Report Name', 'GET', '/members/blahblah', 404],
            'Members/Members - Lapsed' => ['Members/Members - Lapsed', 'GET', '/members/lapsed/18', 200],
            'Members/Members - Lapsed CEM 18mocutoff' => ['Members/Members - Lapsed CEM 18mocutoff', 'GET', '/members/lapsedcem/18', 200],
            'Members/Members - Lapsed CEM Set To Former' => ['Members/Members - Lapsed CEM Set To Former', 'PATCH', '/members/lapsedcem/10', 200],
            'Members/Members - Lapsed CEM all' => ['Members/Members - Lapsed CEM all', 'GET', '/members/lapsedcem/60', 200],
            'Members/Members - Life/Hon' => ['Members/Members - Life/Hon', 'GET', '/members/life_and_hon', 200],
            'Members/Members - Life/Hon Copy' => ['Members/Members - Life/Hon Copy', 'GET', '/members/filter?membertyperange=(5,6)', 200],
            'Members/Members - Map List' => ['Members/Members - Map List', 'GET', '/members/maplist', 200],
            'Members/Members - No Email CSV List' => ['Members/Members - No Email CSV List', 'GET', '/members/noemaillist', 200],
            'Members/Members - No UK Address' => ['Members/Members - No UK Address', 'GET', '/members/noukaddress', 200],
            'Members/Members - Old Former Member' => ['Members/Members - Old Former Member', 'GET', '/members/oldformermember/36', 200],
            'Members/Members - Paying Hon Life' => ['Members/Members - Paying Hon Life', 'GET', '/members/payinghonlife', 200],
            'Name/Name - Check delete on worked' => ['Name/Name - Check delete on worked', 'GET', '/name/6594', 422],
            'Name/Name - Check idmember Update' => ['Name/Name - Check idmember Update', 'GET', '/name/idmember/119', 200],
            'Name/Name - Create' => ['Name/Name - Create', 'POST', '/name', 200],
            'Name/Name - Delete a single name' => ['Name/Name - Delete a single name', 'DELETE', '/name/6594', 200],
            'Name/Name - Delete all names for member' => ['Name/Name - Delete all names for member', 'DELETE', '/name/idmember/419', 200],
            'Name/Name - Read One - No ID' => ['Name/Name - Read One - No ID', 'GET', '/name', 404],
            'Name/Name - Read One - invalid ID' => ['Name/Name - Read One - invalid ID', 'GET', '/name/100', 422],
            'Name/Name - Read One - invalid ID Copy' => ['Name/Name - Read One - invalid ID Copy', 'GET', '/name/idmember/100000', 200],
            'Name/Name - Read One ID' => ['Name/Name - Read One ID', 'GET', '/name/6475', 200],
            'Name/Name - Read from idmember' => ['Name/Name - Read from idmember', 'GET', '/name/idmember/119', 200],
            'Name/Name - Test names are deleted' => ['Name/Name - Test names are deleted', 'GET', '/name/idmember/419', 200],
            'Name/Name - Update Names for Idmember' => ['Name/Name - Update Names for Idmember', 'PUT', '/name/idmember/119', 200],
            'PaymentType/PaymentType - Read' => ['PaymentType/PaymentType - Read', 'GET', '/payment_type', 200],
            'PaymentType/PaymentType - Read One ID Copy' => ['PaymentType/PaymentType - Read One ID Copy', 'GET', '/payment_type/2', 200],
            'PaymentType/PaymentType - Read One Name' => ['PaymentType/PaymentType - Read One Name', 'GET', '/payment_type/cash', 200],
            'Pending/Member - Create Pending' => ['Pending/Member - Create Pending', 'POST', '/member', 200],
            'Pending/Name - Create for Pending' => ['Pending/Name - Create for Pending', 'POST', '/name', 200],
            'Pending/Transaction - Create Pending' => ['Pending/Transaction - Create Pending', 'POST', '/transaction', 200],
            'Status/Status - Read All' => ['Status/Status - Read All', 'GET', '/status', 200],
            'Status/Status - Read One ID' => ['Status/Status - Read One ID', 'GET', '/status/2', 200],
            'Status/Status - Read One Name' => ['Status/Status - Read One Name', 'GET', '/status/Corporate', 200],
            'Transaction/Transaction - Create' => ['Transaction/Transaction - Create', 'POST', '/transaction', 200],
            'Transaction/Transaction - Delete By idmember' => ['Transaction/Transaction - Delete By idmember', 'DELETE', '/transaction/idmember/509', 200],
            'Transaction/Transaction - Read All' => ['Transaction/Transaction - Read All', 'GET', '/transaction', 200],
            'Transaction/Transaction - Read One id' => ['Transaction/Transaction - Read One id', 'GET', '/transaction/3150', 200],
            'Transaction/Transaction - Read One invalid ID' => ['Transaction/Transaction - Read One invalid ID', 'GET', '/transaction/1', 422],
            'Transaction/Transaction - Read idmember' => ['Transaction/Transaction - Read idmember', 'GET', '/transaction/idmember/8', 200],
            'Transaction/Transaction - Verify Delete by idmember' => ['Transaction/Transaction - Verify Delete by idmember', 'GET', '/transaction/idmember/509', 200],
            'Transactions/Transactions: Detail' => ['Transactions/Transactions: Detail', 'GET', '/transactions/detail?month=01&year=2021&bankID=3', 200],
            'Transactions/Transactions: Summary By Month' => ['Transactions/Transactions: Summary By Month', 'GET', '/transactions/summary?start=2021-01-01&end=2021-03-31', 200],
            'Transactions/Transactions: Summary By Month Copy' => ['Transactions/Transactions: Summary By Month Copy', 'GET', '/transactions/summary?start=2021-01-01&end=&bankID=3', 200],
            'Users/Users - Create New' => ['Users/Users - Create New', 'POST', '/user', 200],
            'Users/Users - Get ID of New User' => ['Users/Users - Get ID of New User', 'GET', '/user', 200],
            'Users/Users - Password Complexity' => ['Users/Users - Password Complexity', 'POST', '/user', 422],
            'Users/Users - Read All' => ['Users/Users - Read All', 'GET', '/user', 200],
            'Users/Users - Read All - Test User' => ['Users/Users - Read All - Test User', 'GET', '/user', 401],
            'Users/Users - Read One' => ['Users/Users - Read One', 'GET', '/user/5', 200],
            'Users/Users - Read One -Test User, another\'s details' => ['Users/Users - Read One -Test User, another\'s details', 'GET', '/user/5', 401],
            'Users/Users - Read One -Test User, own details' => ['Users/Users - Read One -Test User, own details', 'GET', '/user/20', 200],
            'Users/Users - Read One -Test User, own details 2' => ['Users/Users - Read One -Test User, own details 2', 'GET', '/user/20', 200],
            'Users/Users - Read One Invalid ID' => ['Users/Users - Read One Invalid ID', 'GET', '/user/5000', 422],
            'Users/Users - Update Copy - Test User, another\'s data' => ['Users/Users - Update Copy - Test User, another\'s data', 'PUT', '/user/6', 401],
            'Users/Users - Update Copy - Test User, own data' => ['Users/Users - Update Copy - Test User, own data', 'PUT', '/user/20', 200],
            'dB Sanity Check/SanityCheck: Deleted but Not Former or CEM' => ['dB Sanity Check/SanityCheck: Deleted but Not Former or CEM', 'GET', '/members/deletedbutnotformer', 200],
            'dB Sanity Check/SanityCheck: lapsed members' => ['dB Sanity Check/SanityCheck: lapsed members', 'GET', '/members/lapsed/24', 200],
            'gocardless/Another Payment' => ['gocardless/Another Payment', 'POST', '/webhook/gocardless', 200],
            'gocardless/Invalid Signature' => ['gocardless/Invalid Signature', 'POST', '/webhook/gocardless', 401],
            'gocardless/Missing Signature' => ['gocardless/Missing Signature', 'POST', '/webhook/gocardless', 400],
            'gocardless/New Mandate' => ['gocardless/New Mandate', 'POST', '/webhook/gocardless', 200],
            'gocardless/Payment Confirmed' => ['gocardless/Payment Confirmed', 'POST', '/webhook/gocardless', 200],
            'gocardless/Signature Validation' => ['gocardless/Signature Validation', 'POST', '/webhook/gocardless', 200],
            'gocardless/Test Route' => ['gocardless/Test Route', 'POST', '/webhook/gocardless', 400],
        ];
    }
}
